"""Generate PROTOCOL.md from the protocol package (SPEC §10).

Non-Python clients implement from the generated doc, not the code.
Run: uv run python scripts/gen_protocol.py   (writes PROTOCOL.md; CI can
diff it to catch undocumented vocabulary drift.)
"""

from __future__ import annotations

from pathlib import Path

from voco.protocol.messages import (
    COMMAND_TYPES,
    EVENT_TYPES,
    PROTOCOL_VERSION,
    TURN_SCOPED,
)

HEADER = f"""\
# voco wire protocol (v{PROTOCOL_VERSION})

GENERATED by scripts/gen_protocol.py from src/voco/protocol/ — edit the
code, not this file. Design rationale: SPEC.md §10.

## Envelope

Every event is one JSON object:

```json
{{"v": {PROTOCOL_VERSION}, "seq": 42, "ts": 1751500000.0,
 "type": "...", "payload": {{}}}}
```

- `seq` is global and monotonic per daemon run; there is NO replay —
  reconnect and read the fresh `snapshot`.
- Consumers MUST ignore unknown types and unknown payload fields
  (additive evolution).
- Wire values use role names, never model names (`first_mate`, not a
  model name).

## Surfaces (localhost only; remote via SSH tunnel)

- `GET  /v1/events` — WebSocket. First message is a `snapshot` event;
  live events follow. Commands may be sent as
  `{{"id": "...", "cmd": "<command>", "payload": {{}}}}`; replies are
  `{{"id": "...", "ok": true, "payload": {{}}}}` or
  `{{"id": "...", "ok": false, "error": "..."}}`.
- `POST /v1/control/<command>` — same commands over HTTP.
- `POST /v1/bridge/register|say|screen`, `GET /v1/bridge/listen` — the
  agent bridge (see SPEC §8.1 for exact payloads and fail-soft rules).
"""


def section(title: str, names: set[str], note: str = "") -> str:
    out = [f"\n## {title}\n"]
    if note:
        out.append(note + "\n")
    for name in sorted(names):
        marker = (
            " *(turn-scoped: payload carries `turn_id`)*" if name in TURN_SCOPED else ""
        )
        out.append(f"- `{name}`{marker}")
    return "\n".join(out) + "\n"


def main() -> None:
    doc = (
        HEADER
        + section(
            "Events (daemon → clients)",
            EVENT_TYPES,
            "Payload shapes are stable per type; see SPEC §10 for semantics.",
        )
        + section("Commands (clients → daemon)", COMMAND_TYPES)
    )
    Path("PROTOCOL.md").write_text(doc)
    n_e, n_c = len(EVENT_TYPES), len(COMMAND_TYPES)
    print(f"PROTOCOL.md written ({n_e} events, {n_c} commands)")


if __name__ == "__main__":
    main()
